# Generated by Django 2.0.2 on 2018-04-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='索引名称')),
                ('fatherid', models.IntegerField(verbose_name='父索引id')),
                ('no', models.CharField(max_length=10, verbose_name='索引编号')),
            ],
        ),
        migrations.CreateModel(
            name='TempParseHtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageNum', models.IntegerField(default=0, verbose_name='文件页码')),
                ('cellText', models.CharField(blank=True, max_length=200, verbose_name='页面元素内容')),
                ('cellCategory', models.CharField(max_length=1, verbose_name='页面元素分类')),
            ],
        ),
    ]
