# Generated by Django 2.0.2 on 2018-04-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempIndexCellCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='索引名称')),
                ('no', models.CharField(max_length=10, verbose_name='索引编号')),
                ('strat_id', models.IntegerField(verbose_name='元素开始位置')),
                ('end_id', models.IntegerField(verbose_name='元素结束位置')),
            ],
        ),
    ]
