# Generated by Django 2.0.2 on 2018-05-11 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majornonwhollyownsubsidiaryfinanciinform',
            name='liquid_asset',
        ),
    ]
