# Generated by Django 2.0.2 on 2018-04-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0002_tempindexcellcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempindexcellcount',
            old_name='strat_id',
            new_name='start_id',
        ),
    ]
