# Generated by Django 2.0.2 on 2018-04-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0003_auto_20180413_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='StdContentIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=2, verbose_name='证券市场')),
                ('name', models.CharField(max_length=100, verbose_name='索引名称')),
                ('no_name', models.CharField(max_length=100, verbose_name='含序号名称')),
                ('fatherno', models.CharField(max_length=10, verbose_name='父级别编码')),
                ('level', models.CharField(max_length=1, verbose_name='编码层次')),
                ('selfno', models.CharField(max_length=2, verbose_name='自身编码')),
                ('no', models.CharField(max_length=10, verbose_name='索引完整编号')),
            ],
        ),
    ]
