# Generated by Django 2.0.2 on 2018-05-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0003_auto_20180511_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majornonwhollyownsubsidiaryfinanciinform',
            name='subject',
            field=models.CharField(choices=[('la', 'liquid_asset'), ('na', 'non_curr_asset'), ('ta', 'total_asset'), ('cl', 'current_liabil'), ('nl', 'non_curr_liabil'), ('tl', 'total_liabil'), ('oi', 'oper_incom'), ('np', 'net_profit'), ('tci', 'total_comprehens_incom'), ('cfo', 'cash_flow_from_oper'), ('cash', 'cash_and_cash_equiva'), ('ms', 'minor_shareholder_equit'), ('na', 'net_asset'), ('nas', 'net_asset_share'), ('adj', 'adjust'), ('goodwil', 'goodwil'), ('itup', 'intern_transact_unreal_profit'), ('oa', 'other_adjust'), ('bvei', 'book_value_of_equiti_invest'), ('fvei', 'fair_value_of_equiti_invest'), ('fe', 'financi_expens'), ('ite', 'incom_tax_expens'), ('donp', 'discontinu_oper_net_profit'), ('oci', 'other_comprehens_incom'), ('dr', 'dividend_receiv')], default='e', max_length=30, verbose_name='项目名称'),
        ),
    ]
