# Generated by Django 2.0.2 on 2018-05-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0004_auto_20180511_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majornonwhollyownsubsidiaryfinanciinform',
            name='subject',
            field=models.CharField(choices=[('1', 'liquid_asset'), ('2', 'non_curr_asset'), ('3', 'total_asset'), ('4', 'current_liabil'), ('5', 'non_curr_liabil'), ('6', 'total_liabil'), ('7', 'oper_incom'), ('8', 'net_profit'), ('9', 'total_comprehens_incom'), ('10', 'cash_flow_from_oper'), ('11', 'cash_and_cash_equiva'), ('12', 'minor_shareholder_equit'), ('13', 'net_asset'), ('14', 'net_asset_share'), ('15', 'adjust'), ('16', 'goodwil'), ('17', 'intern_transact_unreal_profit'), ('18', 'other_adjust'), ('19', 'book_value_of_equiti_invest'), ('20', 'fair_value_of_equiti_invest'), ('21', 'financi_expens'), ('22', 'incom_tax_expens'), ('23', 'discontinu_oper_net_profit'), ('24', 'other_comprehens_incom'), ('25', 'dividend_receiv')], default='e', max_length=30, verbose_name='项目名称'),
        ),
    ]
