# Generated by Django 2.0.2 on 2018-04-14 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0004_stdcontentindex'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stdcontentindex',
            unique_together={('market', 'no')},
        ),
    ]
