# Generated by Django 2.0.2 on 2018-05-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0005_auto_20180511_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprehensnote',
            name='risk_relat_to_financi_instrument',
            field=models.TextField(default='', verbose_name='与金融工具相关的风险'),
        ),
    ]
