# Generated by Django 2.0.2 on 2018-04-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0006_stdcontentindex_has_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempindexcellcount',
            name='end_id',
            field=models.IntegerField(blank=True, verbose_name='元素结束位置'),
        ),
    ]
