# Generated by Django 2.0.2 on 2018-05-11 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0006_comprehensnote_risk_relat_to_financi_instrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCompaniAndActualControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('parent_compani_name', models.CharField(default='', max_length=150, verbose_name='母公司名称')),
                ('registr', models.CharField(default='', max_length=150, verbose_name='注册地')),
                ('busi_natur', models.CharField(default='', max_length=150, verbose_name='业务性质')),
                ('regist_capit', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='注册资本')),
                ('parent_company_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='母公司对本企业的持股比例')),
                ('parent_company_vote_right', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='母公司对本企业的表决权比例')),
                ('actual_control', models.CharField(default='', max_length=150, verbose_name='实际控制人')),
                ('desc', models.TextField(default='', verbose_name='说明')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
                ('typ_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.ReportType', verbose_name='报表类型')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='parentcompaniandactualcontrol',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'parent_compani_name')},
        ),
    ]
