# Generated by Django 2.0.2 on 2018-04-14 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0007_auto_20180414_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempindexcellcount',
            name='end_id',
        ),
    ]
