# Generated by Django 2.0.2 on 2018-05-11 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0007_auto_20180511_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherRelat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('name', models.CharField(default='', max_length=150, unique=True, verbose_name='其他关联方名称')),
                ('relationship', models.CharField(default='', max_length=150, verbose_name='关联关系')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
                ('typ_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.ReportType', verbose_name='报表类型')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='otherrelat',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'name')},
        ),
    ]
