# Generated by Django 2.0.2 on 2018-04-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0008_remove_tempindexcellcount_end_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempindexcellcount',
            name='no',
            field=models.CharField(max_length=10, unique=True, verbose_name='索引编号'),
        ),
    ]
