# Generated by Django 2.0.2 on 2018-04-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0009_auto_20180414_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempindexcellcount',
            name='cell_text',
            field=models.CharField(default='s', max_length=100, verbose_name='源文件文本内容'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stdcontentindex',
            name='has_child',
            field=models.CharField(max_length=1, verbose_name='是否有下一级索引'),
        ),
        migrations.AlterField(
            model_name='tempindexcellcount',
            name='name',
            field=models.CharField(max_length=100, verbose_name='标准索引名称'),
        ),
    ]
