# Generated by Django 2.0.2 on 2018-04-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0010_auto_20180414_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablename', models.CharField(max_length=100, verbose_name='表名')),
                ('fieldname', models.CharField(max_length=100, verbose_name='字段名')),
                ('fieldtype', models.CharField(max_length=100, verbose_name='字段类型')),
                ('maxlengeth', models.IntegerField(verbose_name='字段长度')),
                ('isunique', models.BooleanField(verbose_name='是否唯一')),
                ('ispk', models.BooleanField(verbose_name='是否为关键索引')),
                ('isblank', models.BooleanField(verbose_name='是否可以输入空值')),
                ('isnull', models.BooleanField(verbose_name='数据库显示为空')),
                ('isunique_together', models.BooleanField(verbose_name='是否联合唯一')),
                ('class_str', models.CharField(max_length=200, verbose_name='表文件描述')),
                ('choices', models.TextField(verbose_name='下拉选项')),
                ('functions', models.TextField(verbose_name='表内函数')),
                ('default', models.TextField(verbose_name='默认值')),
                ('verbosename', models.TextField(verbose_name='字段别名')),
                ('foreignkey', models.TextField(verbose_name='外键')),
                ('meta', models.TextField(verbose_name='表相关信息')),
            ],
        ),
        migrations.DeleteModel(
            name='ContentIndex',
        ),
        migrations.AlterField(
            model_name='stdcontentindex',
            name='has_child',
            field=models.CharField(default='0', max_length=1, verbose_name='是否有下一级索引'),
        ),
    ]
