# Generated by Django 2.0.2 on 2018-05-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0011_auto_20180511_1751'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moneylend',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'transact_type', 'name', 'amount', 'start_date', 'expiri_date')},
        ),
    ]
