# Generated by Django 2.0.2 on 2018-04-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0011_auto_20180415_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='roottables',
            name='tableclass',
            field=models.CharField(choices=[('root', 'root'), ('std', 'standard'), ('temp', 'temp'), ('business', 'business')], default=1, max_length=10, verbose_name='表类别'),
            preserve_default=False,
        ),
    ]
