# Generated by Django 2.0.2 on 2018-04-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0012_roottables_tableclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roottables',
            name='choices',
            field=models.TextField(blank=True, verbose_name='下拉选项'),
        ),
        migrations.AlterField(
            model_name='roottables',
            name='class_str',
            field=models.CharField(blank=True, max_length=200, verbose_name='表文件描述'),
        ),
        migrations.AlterField(
            model_name='roottables',
            name='default',
            field=models.TextField(blank=True, verbose_name='默认值'),
        ),
        migrations.AlterField(
            model_name='roottables',
            name='fieldname',
            field=models.CharField(blank=True, max_length=100, verbose_name='字段名'),
        ),
        migrations.AlterField(
            model_name='roottables',
            name='fieldtype',
            field=models.CharField(blank=True, max_length=100, verbose_name='字段类型'),
        ),
        migrations.AlterField(
            model_name='roottables',
            name='foreignkey',
            field=models.TextField(blank=True, verbose_name='外键'),
        ),
        migrations.AlterField(
            model_name='roottables',
            name='functions',
            field=models.TextField(blank=True, verbose_name='表内函数'),
        ),
        migrations.AlterField(
            model_name='roottables',
            name='maxlengeth',
            field=models.IntegerField(blank=True, null=True, verbose_name='字段长度'),
        ),
        migrations.AlterField(
            model_name='roottables',
            name='meta',
            field=models.TextField(blank=True, verbose_name='表相关信息'),
        ),
        migrations.AlterField(
            model_name='roottables',
            name='tableclass',
            field=models.CharField(blank=True, choices=[('root', 'root'), ('std', 'standard'), ('temp', 'temp'), ('business', 'business')], max_length=10, verbose_name='表类别'),
        ),
        migrations.AlterField(
            model_name='roottables',
            name='tablename',
            field=models.CharField(blank=True, max_length=100, verbose_name='表名'),
        ),
        migrations.AlterField(
            model_name='roottables',
            name='verbosename',
            field=models.TextField(blank=True, verbose_name='字段别名'),
        ),
    ]
