# Generated by Django 2.0.2 on 2018-05-11 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0013_auto_20180511_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyManagStaffRemuner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('name', models.CharField(default='', max_length=150, verbose_name='项目')),
                ('end', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='本期发生额')),
                ('before', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='上期发生额')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
                ('typ_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.ReportType', verbose_name='报表类型')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='keymanagstaffremuner',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'name')},
        ),
    ]
