# Generated by Django 2.0.2 on 2018-05-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0014_auto_20180511_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprehensnote',
            name='other_relat_transact',
            field=models.TextField(default='', verbose_name='其他关联交易说明'),
        ),
    ]
