# Generated by Django 2.0.2 on 2018-04-19 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0016_interpret'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexHandleMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_classname', models.CharField(max_length=30, verbose_name='处理类名')),
                ('indexno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.StdContentIndex', unique=True, verbose_name='索引编码')),
            ],
        ),
    ]
