# Generated by Django 2.0.2 on 2018-04-19 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0017_indexhandlemethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexhandlemethod',
            name='indexno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.StdContentIndex', verbose_name='索引编码'),
        ),
    ]
