# Generated by Django 2.0.2 on 2018-04-19 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0018_auto_20180419_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablename', models.CharField(blank=True, max_length=100, unique=True, verbose_name='表英文名')),
                ('table_cn_name', models.CharField(blank=True, max_length=100, verbose_name='表中文名')),
                ('table_desc', models.CharField(blank=True, default='', max_length=200, verbose_name='表文件描述')),
            ],
        ),
        migrations.CreateModel(
            name='StoragRegistrForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('is_exist', models.BooleanField(verbose_name='表是否存在')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.StandardTables', verbose_name='标准表')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='roottabledesc',
            name='class_str',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='表文件描述'),
        ),
        migrations.AlterField(
            model_name='roottabledesc',
            name='functions',
            field=models.TextField(blank=True, default='', verbose_name='表内函数'),
        ),
        migrations.AlterField(
            model_name='roottabledesc',
            name='meta',
            field=models.TextField(blank=True, default='', verbose_name='表相关信息'),
        ),
    ]
