# Generated by Django 2.0.2 on 2018-04-19 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0020_auto_20180419_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniProfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('chines_name', models.CharField(default='', max_length=150, verbose_name='公司的中文名称')),
                ('chines_abbrevi', models.CharField(default='', max_length=150, verbose_name='公司的中文简称')),
                ('foreign_name', models.CharField(default='', max_length=150, verbose_name='公司的外文名称')),
                ('foreign_abbrevi', models.CharField(default='', max_length=150, verbose_name='公司的外文名称缩写')),
                ('legal_repres', models.CharField(default='', max_length=150, verbose_name='公司的法定代表人')),
                ('board_secretary_nam', models.CharField(default='', max_length=150, verbose_name='董秘姓名')),
                ('board_secretary_addr', models.CharField(default='', max_length=150, verbose_name='董秘联系地址')),
                ('board_secretary_tel', models.CharField(default='', max_length=150, verbose_name='董秘联系电话')),
                ('board_secretary_fax', models.CharField(default='', max_length=150, verbose_name='董秘传真')),
                ('board_secretary_email', models.CharField(default='', max_length=150, verbose_name='董秘邮箱')),
                ('compani_regist_addre', models.CharField(default='', max_length=150, verbose_name='公司注册地址')),
                ('postal_regist', models.CharField(default='', max_length=150, verbose_name='公司注册地址的邮政编码')),
                ('compani_offic_addres', models.CharField(default='', max_length=150, verbose_name='公司办公地址')),
                ('postal_offic', models.CharField(default='', max_length=150, verbose_name='公司办公地址的邮政编码')),
                ('compani_websit', models.CharField(default='', max_length=150, verbose_name='公司网址')),
                ('compani_email', models.CharField(default='', max_length=150, verbose_name='公司电子信箱')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='companiprofil',
            unique_together={('stk_cd', 'acc_per')},
        ),
    ]
