# Generated by Django 2.0.2 on 2018-04-20 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0022_auto_20180419_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniBusiOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('major_busi_model_indu', models.TextField(default='', verbose_name='主要业务、经营模式及行业情况')),
                ('major_chang_in_major_asset', models.TextField(default='', verbose_name='主要资产发生重大变化')),
                ('core_competit', models.TextField(default='', verbose_name='核心竞争力')),
                ('major_asset', models.CharField(default='', max_length=150, verbose_name='主要资产')),
                ('descrip', models.TextField(default='', verbose_name='变动原因说明')),
                ('major_oversea_asset', models.TextField(default='', verbose_name='主要境外资产情况')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MajorOverseaAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('asset_contents', models.CharField(default='', max_length=150, verbose_name='资产的具体内容')),
                ('caus_of_format', models.CharField(default='', max_length=150, verbose_name='形成原因')),
                ('asset_size', models.CharField(default='', max_length=150, verbose_name='资产规模')),
                ('locat', models.CharField(default='', max_length=150, verbose_name='所在地')),
                ('oper_mode', models.CharField(default='', max_length=150, verbose_name='运营模式')),
                ('control_measur', models.CharField(default='', max_length=300, verbose_name='保障资产安全性的控制措施')),
                ('revenu_statu', models.CharField(default='', max_length=150, verbose_name='收益状况')),
                ('proport_of_oversea', models.CharField(default='', max_length=150, verbose_name='境外资产占公司净资产的比重')),
                ('impair_risk', models.CharField(default='', max_length=150, verbose_name='是否存在重大减值风险')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
