# Generated by Django 2.0.2 on 2018-04-20 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0023_companibusioverview_majoroverseaasset'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companibusioverview',
            unique_together={('stk_cd', 'acc_per')},
        ),
        migrations.AlterUniqueTogether(
            name='majoroverseaasset',
            unique_together={('stk_cd', 'acc_per')},
        ),
    ]
