# Generated by Django 2.0.2 on 2018-05-12 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0023_auto_20180512_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnOnEquitiAndEarnPerShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('gain_or_loss_type', models.CharField(choices=[('b', 'before_deduct_non_recur'), ('a', 'after_deduct_non_recur')], default='s', max_length=30, verbose_name='收益类别')),
                ('return_on_equiti', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='净资产收益率')),
                ('basic_earn_per_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='基本每股收益')),
                ('dilut_earn_per_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='稀释每股收益')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
                ('typ_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.ReportType', verbose_name='报表类型')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='returnonequitiandearnpershare',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'gain_or_loss_type')},
        ),
    ]
