# Generated by Django 2.0.2 on 2018-04-20 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0024_auto_20180420_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusiSituatDiscussAndAnalysi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('busi_situat_discuss', models.TextField(default='', verbose_name='经营情况讨论与分析')),
                ('major_oper_condit', models.TextField(default='', verbose_name='报告期内主要经营情况')),
                ('revenu_and_cost_anal', models.TextField(default='', verbose_name='收入与成本分析')),
                ('ipr_instructi', models.TextField(default='', verbose_name='分行业、钒产品、分地区主营业务说明')),
                ('psi_instructi', models.TextField(default='', verbose_name='产销量情况说明')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.CreateModel(
            name='CostIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('industry', models.CharField(default='', max_length=150, verbose_name='分行业')),
                ('cost_composit', models.CharField(default='', max_length=120, verbose_name='成本构成')),
                ('thiperiod', models.DecimalField(decimal_places=2, default=0.0, max_digits=26, verbose_name='本期金额')),
                ('lastperiod', models.DecimalField(decimal_places=2, default=0.0, max_digits=26, verbose_name='上期金额')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.CreateModel(
            name='CostProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('product', models.CharField(default='', max_length=150, verbose_name='分产品')),
                ('cost_composit', models.CharField(default='', max_length=120, verbose_name='成本构成')),
                ('thiperiod', models.DecimalField(decimal_places=2, default=0.0, max_digits=26, verbose_name='本期金额')),
                ('lastperiod', models.DecimalField(decimal_places=2, default=0.0, max_digits=26, verbose_name='上期金额')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.CreateModel(
            name='CostSubRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('region', models.CharField(default='', max_length=150, verbose_name='分地区')),
                ('cost_composit', models.CharField(default='', max_length=120, verbose_name='成本构成')),
                ('thiperiod', models.DecimalField(decimal_places=2, default=0.0, max_digits=26, verbose_name='本期金额')),
                ('lastperiod', models.DecimalField(decimal_places=2, default=0.0, max_digits=26, verbose_name='上期金额')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.CreateModel(
            name='MainBusiSubIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('industry', models.CharField(default='', max_length=150, verbose_name='分行业')),
                ('income', models.DecimalField(decimal_places=2, default=0.0, max_digits=26, verbose_name='营业收入')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=26, verbose_name='营业成本')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.CreateModel(
            name='MainBusiSubProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('product', models.CharField(default='', max_length=150, verbose_name='分产品')),
                ('income', models.DecimalField(decimal_places=2, default=0.0, max_digits=26, verbose_name='营业收入')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=26, verbose_name='营业成本')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.CreateModel(
            name='MainBusiSubRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('region', models.CharField(default='', max_length=150, verbose_name='分产品')),
                ('income', models.DecimalField(decimal_places=2, default=0.0, max_digits=26, verbose_name='营业收入')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=26, verbose_name='营业成本')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAndSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('product_vol', models.CharField(default='', max_length=150, verbose_name='生产量')),
                ('sale_vol', models.CharField(default='', max_length=150, verbose_name='销售量')),
                ('inventori_vol', models.CharField(default='', max_length=150, verbose_name='库存量')),
                ('main_product', models.CharField(default='', max_length=150, verbose_name='主要产品')),
                ('unit', models.CharField(default='', max_length=150, verbose_name='单位')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='mainbusisubregion',
            unique_together={('stk_cd', 'acc_per', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='mainbusisubproduct',
            unique_together={('stk_cd', 'acc_per', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='mainbusisubindustry',
            unique_together={('stk_cd', 'acc_per', 'industry')},
        ),
        migrations.AlterUniqueTogether(
            name='costsubregion',
            unique_together={('stk_cd', 'acc_per', 'region', 'cost_composit')},
        ),
        migrations.AlterUniqueTogether(
            name='costproduct',
            unique_together={('stk_cd', 'acc_per', 'product', 'cost_composit')},
        ),
        migrations.AlterUniqueTogether(
            name='costindustry',
            unique_together={('stk_cd', 'acc_per', 'industry', 'cost_composit')},
        ),
        migrations.AlterUniqueTogether(
            name='busisituatdiscussandanalysi',
            unique_together={('stk_cd', 'acc_per')},
        ),
    ]
