# Generated by Django 2.0.2 on 2018-05-13 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0025_auto_20180513_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailForSaleFinanciAssetCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('name', models.CharField(default='', max_length=150, verbose_name='被投资单位')),
                ('b_book_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='账面余额期初')),
                ('i_book_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='账面余额本期增加')),
                ('c_book_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='账面余额本期减少')),
                ('e_book_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='账面余额期末')),
                ('b_impair', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='减值准备年初')),
                ('i_impair', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='减值准备本期增加')),
                ('c_impair', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='减值准备本期减少')),
                ('e_impair', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='减值准备期末')),
                ('proport_of_share_held', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='在被投资单位持股比例')),
                ('cash_bonu', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='本年现金红利')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
                ('typ_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.ReportType', verbose_name='报表类型')),
            ],
        ),
        migrations.CreateModel(
            name='AvailForSaleFinanciAssetFair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('name', models.CharField(default='', max_length=150, verbose_name='项目分类')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='权益工具的成本/债务工具的摊余成本')),
                ('fair_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='公允价值')),
                ('accumul_into_other_comprehens_incom', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='累计计入其他综合收益的公允价值变动金额')),
                ('impair', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='已计提减值金额')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
                ('typ_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.ReportType', verbose_name='报表类型')),
            ],
        ),
        migrations.AlterField(
            model_name='commonbalancimpairnet',
            name='subject',
            field=models.CharField(choices=[('inventori', 'inventori'), ('construct_in_progress', 'construct_in_progress'), ('longterm_equiti_invest', 'longterm_equiti_invest'), ('avail_for_sale_financi_asset', 'avail_for_sale_financi_asset')], default='', max_length=30, verbose_name='科目名称'),
        ),
        migrations.AlterField(
            model_name='commonbeforeandendname',
            name='subject',
            field=models.CharField(choices=[('interest_receiv', 'interest_receiv'), ('dividend_receiv', 'dividend_receiv'), ('other_receiv_natur', 'other_receiv_natur'), ('noncurr_asset_due_within_one_year', 'noncurr_asset_due_within_one_year'), ('other_current_asset', 'other_current_asset'), ('engin_materi', 'engin_materi'), ('fix_asset_clean_up', 'fix_asset_clean_up'), ('unconfirm_defer_incom_tax', 'unconfirm_defer_incom_tax'), ('expir_in_the_follow_year', 'expir_in_the_follow_year'), ('other_noncurr_asset', 'other_noncurr_asset'), ('shortterm_loan', 'shortterm_loan'), ('financi_liabil_measur_at_fair_valu', 'financi_liabil_measur_at_fair_valu'), ('bill_payabl', 'bill_payabl'), ('account_payabl', 'account_payabl'), ('advanc_receipt', 'advanc_receipt'), ('tax_payabl', 'tax_payabl'), ('interest_payabl', 'interest_payabl'), ('other_payabl', 'other_payabl'), ('noncurr_liabil_due_within_one_year', 'noncurr_liabil_due_within_one_year'), ('bond_payabl', 'bond_payabl'), ('undistributed_profit', 'undistributed_profit'), ('tax_and_surcharg', 'tax_and_surcharg'), ('sale_expens', 'sale_expens'), ('manag_cost', 'manag_cost'), ('financi_expens', 'financi_expens'), ('asset_impair_loss', 'asset_impair_loss'), ('chang_in_fair_valu', 'chang_in_fair_valu'), ('invest_incom', 'invest_incom'), ('nonoper_incom', 'nonoper_incom'), ('nonoper_expens', 'nonoper_expens'), ('incom_tax_expens', 'incom_tax_expens'), ('profit_to_incometax', 'profit_to_incometax'), ('receipt_other_busi', 'receipt_other_busi'), ('payment_other_busi', 'payment_other_busi'), ('receipt_other_invest', 'receipt_other_invest'), ('payment_other_invest', 'payment_other_invest'), ('receipt_other_financ', 'receipt_other_financ'), ('payment_other_financ', 'payment_other_financ'), ('addit_materi', 'addit_materi'), ('composit_of_cash_and_cash_equival', 'composit_of_cash_and_cash_equival'), ('asset_with_limit_ownership', 'asset_with_limit_ownership'), ('govern_subsidi', 'govern_subsidi'), ('nonrecur_gain_and_loss', 'nonrecur_gain_and_loss')], default='', max_length=30, verbose_name='科目名称'),
        ),
        migrations.AlterUniqueTogether(
            name='availforsalefinanciassetfair',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='availforsalefinanciassetcost',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'name')},
        ),
    ]
