# Generated by Django 2.0.2 on 2018-04-21 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0025_auto_20180420_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorCustomAndSupplie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('major_class', models.CharField(blank=True, choices=[('custom', 'custom'), ('suppli', 'suppli')], max_length=6, verbose_name='客户/供应商')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=26, verbose_name='前五大金额')),
                ('amount_prop', models.DecimalField(decimal_places=2, default=0.0, max_digits=26, verbose_name='前五大占比')),
                ('amount_relat', models.DecimalField(decimal_places=2, default=0.0, max_digits=26, verbose_name='前五大中关联方金额')),
                ('amount_relat_prop', models.DecimalField(decimal_places=2, default=0.0, max_digits=26, verbose_name='前五大中关联方占比')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.CreateModel(
            name='MajorCustomAndSupplieDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('major_class', models.CharField(blank=True, choices=[('custom', 'custom'), ('suppli', 'suppli')], max_length=6, verbose_name='客户/供应商')),
                ('name', models.CharField(blank=True, default='', max_length=150, verbose_name='名称')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=26, verbose_name='金额')),
                ('amount_prop', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='占比')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.AddField(
            model_name='busisituatdiscussandanalysi',
            name='ca_instructi',
            field=models.TextField(default='', verbose_name='成本分析情况说明'),
        ),
        migrations.AddField(
            model_name='busisituatdiscussandanalysi',
            name='mfcs_instructi',
            field=models.TextField(default='', verbose_name='前五大客户及供应商说明'),
        ),
        migrations.AlterField(
            model_name='busisituatdiscussandanalysi',
            name='ipr_instructi',
            field=models.TextField(default='', verbose_name='分行业、分产品、分地区主营业务说明'),
        ),
        migrations.AlterUniqueTogether(
            name='majorcustomandsuppliedetail',
            unique_together={('stk_cd', 'acc_per', 'major_class', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='majorcustomandsupplie',
            unique_together={('stk_cd', 'acc_per', 'major_class')},
        ),
    ]
