# Generated by Django 2.0.2 on 2018-04-21 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0026_auto_20180421_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensAnalysi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('name', models.CharField(blank=True, default='', max_length=150, verbose_name='费用名称')),
                ('instruct', models.CharField(blank=True, default='', max_length=500, verbose_name='变动原因说明')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.AddField(
            model_name='busisituatdiscussandanalysi',
            name='ea_instructi',
            field=models.TextField(default='', verbose_name='费用变动分析'),
        ),
        migrations.AlterUniqueTogether(
            name='expensanalysi',
            unique_together={('stk_cd', 'acc_per', 'name')},
        ),
    ]
