# Generated by Django 2.0.2 on 2018-05-14 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0027_auto_20180513_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquireRecognisAssetAndLiab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('value_type', models.CharField(choices=[('f', 'fair'), ('b', 'book')], default='f', max_length=30, verbose_name='价值类型')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='金额')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyName', verbose_name='公司名称')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.SubjectName', verbose_name='科目名称')),
                ('typ_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.ReportType', verbose_name='报表类型')),
            ],
        ),
        migrations.CreateModel(
            name='AvailForSaleFinanciAssetNoImpairDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('name', models.CharField(default='', max_length=150, verbose_name='可供出售权益工具项目')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='投资成本')),
                ('fair_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='年末公允价值')),
                ('fall_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='公允价值相对于成本的下跌幅度')),
                ('continu_fall_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='持续下跌时间')),
                ('impair', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='已计提减值金额')),
                ('reason', models.TextField(default='', verbose_name='未计提减值准备原因')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
                ('typ_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.ReportType', verbose_name='报表类型')),
            ],
        ),
        migrations.CreateModel(
            name='BookValuOfAssetAndLiabil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('deadlin', models.CharField(choices=[('m', 'merger_date'), ('b', 'before')], default='f', max_length=30, verbose_name='截止日期')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='金额')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyName', verbose_name='公司名称')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.SubjectName', verbose_name='科目名称')),
                ('typ_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.ReportType', verbose_name='报表类型')),
            ],
        ),
        migrations.CreateModel(
            name='BusiMergerNotUnderTheSameControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('acquisit_time', models.CharField(default='', max_length=150, verbose_name='股权取得时点')),
                ('acquisit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='股权取得成本')),
                ('acquisit_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='股权取得比例')),
                ('acquisit_style', models.CharField(default='', max_length=150, verbose_name='取得方式')),
                ('purchas_day', models.CharField(default='', max_length=150, verbose_name='购买日')),
                ('purchas_day_determi_basi', models.CharField(default='', max_length=300, verbose_name='购买日的确定依据')),
                ('income', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='购买日至期末被购买方的收入')),
                ('np', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='购买日至期末被购买方的净利润')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyName', verbose_name='被购买方名称')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
                ('typ_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.ReportType', verbose_name='报表类型')),
            ],
        ),
        migrations.CreateModel(
            name='BusiMergerUnderTheSameControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('acquisit_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='企业合并中取得的权益比例')),
                ('same_control_basi', models.CharField(default='', max_length=150, verbose_name='构成同一控制下企业合并的依据')),
                ('merger_date', models.CharField(default='', max_length=150, verbose_name='合并日')),
                ('merger_date_determi_basi', models.CharField(default='', max_length=300, verbose_name='合并日的确定依据')),
                ('this_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='合并当期期初至合并日被合并方的收入')),
                ('this_np', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='合并当期期初至合并日被合并方的净利润')),
                ('before_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='比较期间被合并方的收入')),
                ('before_np', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='比较期间被合并方的净利润')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyName', verbose_name='被合并方名称')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
                ('typ_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.ReportType', verbose_name='报表类型')),
            ],
        ),
        migrations.CreateModel(
            name='ConsolidCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='现金')),
                ('non_cash_asset', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='非现金资产的账面价值')),
                ('issu_or_assum_debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='发行或承担的债务的账面价值')),
                ('issuanc_of_equiti_secur', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='发行的权益性证券的面值')),
                ('or_have_consider', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='或有对价')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyName', verbose_name='单位名称')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
                ('typ_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.ReportType', verbose_name='报表类型')),
            ],
        ),
        migrations.CreateModel(
            name='ConsolidCostAndGoodwil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='现金')),
                ('non_cash_asset', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='非现金资产的公允价值')),
                ('issu_or_assum_debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='发行或承担的债务的公允价值')),
                ('issuanc_of_equiti_secur', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='发行的权益性证券的公允价值')),
                ('or_have_consider', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='或有对价的公允价值')),
                ('share_held_prior_to_the_acquis', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='购买日之前持有的股权于购买日的公允价值')),
                ('other', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='其他')),
                ('total_combin_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='合并成本合计')),
                ('recogniz_net_asset_fair_valu', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='减：取得的可辨认净资产公允价值份额')),
                ('goodwil', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='商誉/合并成本小于取得的可辨认净资产公允价值份额的金额')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyName', verbose_name='被购买方名称')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
                ('typ_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.ReportType', verbose_name='报表类型')),
            ],
        ),
        migrations.CreateModel(
            name='OverduShorttermBorrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('name', models.CharField(default='', max_length=150, verbose_name='借款单位')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='期末金额')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='借款利率')),
                ('overdu_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='逾期利率')),
                ('overdu_time', models.CharField(default='', max_length=150, verbose_name='逾期时间')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
                ('typ_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.ReportType', verbose_name='报表类型')),
            ],
        ),
        migrations.CreateModel(
            name='SignificHeldToMaturInvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('name', models.CharField(default='', max_length=150, verbose_name='债券项目')),
                ('book_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='面值')),
                ('book_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='票面利率')),
                ('real_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='实际利率')),
                ('expiri_date', models.CharField(default='', max_length=300, verbose_name='到期日')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
                ('typ_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.ReportType', verbose_name='报表类型')),
            ],
        ),
        migrations.AddField(
            model_name='comprehensnote',
            name='chang_in_consolid_scope_with_other_reason',
            field=models.TextField(default='', verbose_name='其他原因的合并范围变动'),
        ),
        migrations.AddField(
            model_name='comprehensnote',
            name='consolid_cost',
            field=models.TextField(default='', verbose_name='同一控制下企业合并:合并成本'),
        ),
        migrations.AddField(
            model_name='comprehensnote',
            name='consolid_cost_and_goodwil',
            field=models.TextField(default='', verbose_name='非同一控制下企业合并:合并成本和商誉'),
        ),
        migrations.AddField(
            model_name='comprehensnote',
            name='revers_purchas',
            field=models.TextField(default='', verbose_name='反向购买'),
        ),
        migrations.AlterField(
            model_name='commonbalancimpairnet',
            name='subject',
            field=models.CharField(choices=[('inventori', 'inventori'), ('construct_in_progress', 'construct_in_progress'), ('longterm_equiti_invest', 'longterm_equiti_invest'), ('avail_for_sale_financi_asset', 'avail_for_sale_financi_asset'), ('held_to_matur_invest', 'held_to_matur_invest'), ('longterm_receiv', 'longterm_receiv')], default='', max_length=30, verbose_name='科目名称'),
        ),
        migrations.AlterField(
            model_name='commonbeforeandendname',
            name='subject',
            field=models.CharField(choices=[('interest_receiv', 'interest_receiv'), ('dividend_receiv', 'dividend_receiv'), ('other_receiv_natur', 'other_receiv_natur'), ('noncurr_asset_due_within_one_year', 'noncurr_asset_due_within_one_year'), ('other_current_asset', 'other_current_asset'), ('construct_in_progres', 'construct_in_progres'), ('engin_materi', 'engin_materi'), ('fix_asset_clean_up', 'fix_asset_clean_up'), ('unconfirm_defer_incom_tax', 'unconfirm_defer_incom_tax'), ('expir_in_the_follow_year', 'expir_in_the_follow_year'), ('other_noncurr_asset', 'other_noncurr_asset'), ('shortterm_loan', 'shortterm_loan'), ('financi_liabil_measur_at_fair_valu', 'financi_liabil_measur_at_fair_valu'), ('bill_payabl', 'bill_payabl'), ('account_payabl', 'account_payabl'), ('advanc_receipt', 'advanc_receipt'), ('tax_payabl', 'tax_payabl'), ('interest_payabl', 'interest_payabl'), ('other_payabl', 'other_payabl'), ('liabil_held_for_sale', 'liabil_held_for_sale'), ('noncurr_liabil_due_within_one_year', 'noncurr_liabil_due_within_one_year'), ('long_term_loan', 'long_term_loan'), ('bond_payabl', 'bond_payabl'), ('longterm_payabl', 'longterm_payabl'), ('estim_liabil', 'estim_liabil'), ('other_noncurr_liabi', 'other_noncurr_liabi'), ('undistributed_profit', 'undistributed_profit'), ('tax_and_surcharg', 'tax_and_surcharg'), ('sale_expens', 'sale_expens'), ('manag_cost', 'manag_cost'), ('financi_expens', 'financi_expens'), ('asset_impair_loss', 'asset_impair_loss'), ('chang_in_fair_valu', 'chang_in_fair_valu'), ('invest_incom', 'invest_incom'), ('asset_dispos_incom', 'asset_dispos_incom'), ('other_incom', 'other_incom'), ('nonoper_incom', 'nonoper_incom'), ('nonoper_expens', 'nonoper_expens'), ('incom_tax_expens', 'incom_tax_expens'), ('receipt_other_busi', 'receipt_other_busi'), ('payment_other_busi', 'payment_other_busi'), ('receipt_other_invest', 'receipt_other_invest'), ('payment_other_invest', 'payment_other_invest'), ('receipt_other_financ', 'receipt_other_financ'), ('payment_other_financ', 'payment_other_financ'), ('addit_materi', 'addit_materi'), ('composit_of_cash_and_cash_equival', 'composit_of_cash_and_cash_equival'), ('asset_with_limit_ownership', 'asset_with_limit_ownership'), ('govern_subsidi', 'govern_subsidi'), ('nonrecur_gain_and_loss', 'nonrecur_gain_and_loss')], default='', max_length=30, verbose_name='科目名称'),
        ),
        migrations.AlterField(
            model_name='commonbicename',
            name='subject',
            field=models.CharField(choices=[('goodwil_impair', 'goodwil_impair'), ('special_payabl', 'special_payabl'), ('capit_reserv', 'capit_reserv'), ('stock', 'stock'), ('other_comprehens_incom', 'other_comprehens_incom'), ('special_reserv', 'special_reserv'), ('surplu_reserv', 'surplu_reserv')], default='', max_length=30, verbose_name='科目名称'),
        ),
        migrations.AlterUniqueTogether(
            name='significheldtomaturinvest',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='overdushorttermborrow',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='consolidcostandgoodwil',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='consolidcost',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='busimergerunderthesamecontrol',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='busimergernotunderthesamecontrol',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='bookvaluofassetandliabil',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'company_name', 'deadlin', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='availforsalefinanciassetnoimpairdesc',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='acquirerecognisassetandliab',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'company_name', 'value_type', 'subject')},
        ),
    ]
