# Generated by Django 2.0.2 on 2018-04-21 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0027_auto_20180421_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDInvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('expens', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='本期费用化研发投入')),
                ('capit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='本期资本化研发投入')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='研发投入合计')),
                ('proport_of_incom', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='研发投入总额占营业收入比例')),
                ('staff_number', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='公司研发人员的数量')),
                ('proport_of_staff', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='研发人员数量占公司总人数的比例')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rdinvest',
            unique_together={('stk_cd', 'acc_per')},
        ),
    ]
