# Generated by Django 2.0.2 on 2018-05-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0028_auto_20180514_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactImpactInChangeShareOfSubsidiari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('project_name', models.CharField(default='', max_length=150, verbose_name='项目名称')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='金额')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyName', verbose_name='公司名称')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
                ('typ_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.ReportType', verbose_name='报表类型')),
            ],
        ),
        migrations.AddField(
            model_name='comprehensnote',
            name='chang_share_of_owner_equiti_in_subsidiari',
            field=models.TextField(default='', verbose_name='在子公司所有者权益份额发生变化的情况说明'),
        ),
        migrations.AlterUniqueTogether(
            name='transactimpactinchangeshareofsubsidiari',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'name', 'project_name')},
        ),
    ]
