# Generated by Django 2.0.2 on 2018-05-14 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0029_auto_20180514_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDivisFinanciInform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('project_name', models.CharField(default='', max_length=150, verbose_name='项目名称')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='金额')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyName', verbose_name='报告分部')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
                ('typ_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.ReportType', verbose_name='报表类型')),
            ],
        ),
        migrations.AddField(
            model_name='comprehensnote',
            name='determin_basi_and_account_report_divis',
            field=models.TextField(default='', verbose_name='报告分部的确定依据与会计政策'),
        ),
        migrations.AddField(
            model_name='comprehensnote',
            name='other_import_transact_and_event',
            field=models.TextField(default='', verbose_name='其他对投资者决策有影响的重要事项'),
        ),
        migrations.AlterUniqueTogether(
            name='reportdivisfinanciinform',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'name', 'project_name')},
        ),
    ]
