# Generated by Django 2.0.2 on 2018-04-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0029_auto_20180421_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdinvest',
            name='expens',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='本期费用化研发投入'),
        ),
    ]
