# Generated by Django 2.0.2 on 2018-05-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0030_auto_20180514_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdivisfinanciinform',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='transactimpactinchangeshareofsubsidiari',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='金额'),
        ),
    ]
