# Generated by Django 2.0.2 on 2018-04-21 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0030_auto_20180421_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowAnalysi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('item', models.CharField(blank=True, default='', max_length=150, verbose_name='现金流量表项目')),
                ('desc', models.CharField(blank=True, default='', max_length=150, verbose_name='现金流量表项目变动原因说明')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.AddField(
            model_name='busisituatdiscussandanalysi',
            name='cfa_instructi',
            field=models.TextField(default='', verbose_name='现金流量表变动分析'),
        ),
        migrations.AlterField(
            model_name='costindustry',
            name='lastperiod',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='上期金额'),
        ),
        migrations.AlterField(
            model_name='costindustry',
            name='thiperiod',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='本期金额'),
        ),
        migrations.AlterField(
            model_name='costproduct',
            name='lastperiod',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='上期金额'),
        ),
        migrations.AlterField(
            model_name='costproduct',
            name='thiperiod',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='本期金额'),
        ),
        migrations.AlterField(
            model_name='costsubregion',
            name='lastperiod',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='上期金额'),
        ),
        migrations.AlterField(
            model_name='costsubregion',
            name='thiperiod',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='本期金额'),
        ),
        migrations.AlterField(
            model_name='mainbusisubindustry',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='营业成本'),
        ),
        migrations.AlterField(
            model_name='mainbusisubindustry',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='营业收入'),
        ),
        migrations.AlterField(
            model_name='mainbusisubproduct',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='营业成本'),
        ),
        migrations.AlterField(
            model_name='mainbusisubproduct',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='营业收入'),
        ),
        migrations.AlterField(
            model_name='mainbusisubregion',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='营业成本'),
        ),
        migrations.AlterField(
            model_name='mainbusisubregion',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='营业收入'),
        ),
        migrations.AlterField(
            model_name='majorcustomandsupplie',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='前五大金额'),
        ),
        migrations.AlterField(
            model_name='majorcustomandsupplie',
            name='amount_prop',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='前五大占比'),
        ),
        migrations.AlterField(
            model_name='majorcustomandsupplie',
            name='amount_relat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='前五大中关联方金额'),
        ),
        migrations.AlterField(
            model_name='majorcustomandsupplie',
            name='amount_relat_prop',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='前五大中关联方占比'),
        ),
        migrations.AlterField(
            model_name='majorcustomandsuppliedetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='rdinvest',
            name='capit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='本期资本化研发投入'),
        ),
        migrations.AlterField(
            model_name='rdinvest',
            name='proport_of_incom',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='研发投入总额占营业收入比例'),
        ),
        migrations.AlterField(
            model_name='rdinvest',
            name='proport_of_staff',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='研发人员数量占公司总人数的比例'),
        ),
        migrations.AlterField(
            model_name='rdinvest',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='研发投入合计'),
        ),
        migrations.AlterUniqueTogether(
            name='cashflowanalysi',
            unique_together={('stk_cd', 'acc_per', 'item')},
        ),
    ]
