# Generated by Django 2.0.2 on 2018-05-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0031_auto_20180514_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorholdcompani',
            name='regist_capit',
            field=models.CharField(default='', max_length=50, verbose_name='注册资本'),
        ),
    ]
