# Generated by Django 2.0.2 on 2018-05-16 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0032_auto_20180516_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busisituatdiscussandanalysi',
            old_name='mhca_instructi',
            new_name='main_sharehold_compani_analysi',
        ),
    ]
