# Generated by Django 2.0.2 on 2018-04-21 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0032_auto_20180421_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('item', models.CharField(blank=True, default='', max_length=150, verbose_name='资产项目')),
                ('desc', models.CharField(blank=True, default='', max_length=150, verbose_name='资产受限情况说明')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.AddField(
            model_name='busisituatdiscussandanalysi',
            name='la_instructi',
            field=models.TextField(default='', verbose_name='受限资产情况说明'),
        ),
        migrations.AlterUniqueTogether(
            name='limitasset',
            unique_together={('stk_cd', 'acc_per', 'item')},
        ),
    ]
