# Generated by Django 2.0.2 on 2018-04-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0033_auto_20180421_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='busisituatdiscussandanalysi',
            name='ioia_instructi',
            field=models.TextField(default='', verbose_name='行业经营性信息分析'),
        ),
    ]
