# Generated by Django 2.0.2 on 2018-05-16 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0034_auto_20180516_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysiOfGuarante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('related', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='为股东、实际控制人及其关联方提供担保的余额')),
                ('asset_li_ratio_exce_70_per', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='直接或间接为资产负债率超过70%的被担保对象提供的债务担保余额')),
                ('more_than_50_per_of_net_asset', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='担保总额超过净资产50%部分的金额')),
                ('sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='担保分析合计')),
                ('warranti_respons_desc', models.TextField(default='', verbose_name='对未到期担保，报告期内已发生担保责任或可能承担连带清偿责任的情况说明')),
                ('non_compli_guarante', models.TextField(default='', verbose_name='违反规定程序对外提供担保的说明')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.CreateModel(
            name='ExternGuarante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('object_classify', models.CharField(choices=[('A', 'extern_company'), ('B', 'subsidiari'), ('C', 'subsidiari_to_subsidiari')], default='B', max_length=30, verbose_name='担保对象分类')),
                ('date_of_disclosur', models.CharField(default='', max_length=150, verbose_name='担保额度相关公告披露日期')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='担保额度')),
                ('actual_date_of_occurr', models.CharField(default='', max_length=150, verbose_name='实际发生日期')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='实际担保金额')),
                ('type', models.CharField(default='', max_length=150, verbose_name='担保类型')),
                ('period', models.CharField(default='', max_length=150, verbose_name='担保期')),
                ('is_complet', models.CharField(default='', max_length=1, verbose_name='是否履行完毕')),
                ('is_related', models.CharField(default='', max_length=1, verbose_name='是否为关联方担保')),
            ],
        ),
        migrations.CreateModel(
            name='GuaranteAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('object_classify', models.CharField(choices=[('A', 'extern_company'), ('B', 'subsidiari'), ('C', 'subsidiari_to_subsidiari'), ('sum', 'sum')], default='B', max_length=30, verbose_name='担保对象分类')),
                ('approv_amount_due_period', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='报告期内审批的对外担保额度合计')),
                ('actual_amount_due_period', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='报告期内实际发生额')),
                ('approv_amount_end_period', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='报告期末已审批的对外担保额度合计')),
                ('actual_amount_end_period', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='报告期末实际对外担保余额合计')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.AlterField(
            model_name='companyname',
            name='natur_of_the_unit',
            field=models.CharField(choices=[('s', 'subcompani'), ('j', 'joint_ventur'), ('p', 'pool'), ('g', 'guaranted')], default='s', max_length=30, verbose_name='单位性质'),
        ),
        migrations.AddField(
            model_name='externguarante',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyName', verbose_name='担保对象名称'),
        ),
        migrations.AddField(
            model_name='externguarante',
            name='stk_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码'),
        ),
        migrations.AlterUniqueTogether(
            name='guaranteamount',
            unique_together={('stk_cd', 'acc_per', 'object_classify')},
        ),
        migrations.AlterUniqueTogether(
            name='externguarante',
            unique_together={('stk_cd', 'acc_per', 'object_classify', 'company_name')},
        ),
        migrations.AlterUniqueTogether(
            name='analysiofguarante',
            unique_together={('stk_cd', 'acc_per')},
        ),
    ]
