# Generated by Django 2.0.2 on 2018-04-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0034_busisituatdiscussandanalysi_ioia_instructi'),
    ]

    operations = [
        migrations.AddField(
            model_name='busisituatdiscussandanalysi',
            name='mhca_instructi',
            field=models.TextField(default='', verbose_name='主要参股公司分析'),
        ),
    ]
