# Generated by Django 2.0.2 on 2018-04-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0035_busisituatdiscussandanalysi_mhca_instructi'),
    ]

    operations = [
        migrations.AddField(
            model_name='busisituatdiscussandanalysi',
            name='industri_structur_and_trend',
            field=models.TextField(default='', verbose_name='行业格局和趋势'),
        ),
    ]
