# Generated by Django 2.0.2 on 2018-05-17 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0035_auto_20180516_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyname',
            name='acc_per',
            field=models.DateField(default='2017-12-31', verbose_name='会计期间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyname',
            name='stk_cd',
            field=models.ForeignKey(default='600001', on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyname',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='公司名称'),
        ),
        migrations.AlterUniqueTogether(
            name='companyname',
            unique_together={('stk_cd', 'acc_per', 'name')},
        ),
    ]
