# Generated by Django 2.0.2 on 2018-05-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0036_auto_20180517_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcompaniandactualcontrol',
            name='regist_capit',
            field=models.CharField(default='', max_length=150, verbose_name='注册资本'),
        ),
    ]
