# Generated by Django 2.0.2 on 2018-04-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0036_busisituatdiscussandanalysi_industri_structur_and_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='busisituatdiscussandanalysi',
            name='comp_develop_strategi',
            field=models.TextField(default='', verbose_name='公司发展战略'),
        ),
    ]
