# Generated by Django 2.0.2 on 2018-05-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0037_auto_20180517_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdividendpolici',
            name='distribut_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='可分配利润'),
        ),
        migrations.AlterField(
            model_name='cashdividendpolici',
            name='prop_of_distribut_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='占可分配利润比例'),
        ),
    ]
