# Generated by Django 2.0.2 on 2018-04-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0037_busisituatdiscussandanalysi_comp_develop_strategi'),
    ]

    operations = [
        migrations.AddField(
            model_name='busisituatdiscussandanalysi',
            name='bussi_plan',
            field=models.TextField(default='', verbose_name='公司经营计划'),
        ),
        migrations.AddField(
            model_name='busisituatdiscussandanalysi',
            name='possibl_risk',
            field=models.TextField(default='', verbose_name='可能面临的风险'),
        ),
    ]
