# Generated by Django 2.0.2 on 2018-05-17 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0038_auto_20180517_1031'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fixasset',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'asset_type', 'valu_categori', 'item', 'increas_cut_back_type', 'amount_type')},
        ),
    ]
