# Generated by Django 2.0.2 on 2018-04-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0038_auto_20180421_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='busisituatdiscussandanalysi',
            name='busi_chang',
            field=models.TextField(default='', verbose_name='主营业务调整及变化情况'),
        ),
    ]
