# Generated by Django 2.0.2 on 2018-04-22 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0039_busisituatdiscussandanalysi_busi_chang'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquitiInvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('name_of_invest_compa', models.CharField(default='', max_length=150, verbose_name='被投资公司名称')),
                ('main_busi', models.CharField(default='', max_length=500, verbose_name='主要业务')),
                ('invest_method', models.CharField(default='', max_length=150, verbose_name='投资方式')),
                ('invest_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='投资金额')),
                ('sharehold_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='投资比例')),
                ('sourc_of_fund', models.CharField(default='', max_length=150, verbose_name='资金来源')),
                ('partner', models.CharField(default='', max_length=150, verbose_name='合作方')),
                ('invest_period', models.CharField(default='', max_length=150, verbose_name='投资期限')),
                ('product_type', models.CharField(default='', max_length=150, verbose_name='产品类型')),
                ('progress', models.CharField(default='', max_length=500, verbose_name='投资进展')),
                ('expect_revenu', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='预计收益')),
                ('current_invest_gain', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='本期收益')),
                ('involv_litig', models.CharField(default='', max_length=150, verbose_name='是否涉诉')),
                ('date_of_disclosur', models.CharField(default='', max_length=150, verbose_name='披露日期')),
                ('disclosur_index', models.CharField(default='', max_length=500, verbose_name='披露索引')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.CreateModel(
            name='OveralInvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('this_period', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='本期投资额')),
                ('last_period', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='上期投资额')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='overalinvest',
            unique_together={('stk_cd', 'acc_per')},
        ),
        migrations.AlterUniqueTogether(
            name='equitiinvest',
            unique_together={('stk_cd', 'acc_per', 'name_of_invest_compa')},
        ),
    ]
