# Generated by Django 2.0.2 on 2018-05-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0039_auto_20180517_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toptensharehold',
            name='end_hold_num',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='期末持股数量'),
        ),
        migrations.AlterField(
            model_name='toptensharehold',
            name='increas_and_decreas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='报告期内增减'),
        ),
        migrations.AlterField(
            model_name='toptensharehold',
            name='restrict_share',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='持有有限售条件股份数量'),
        ),
        migrations.AlterField(
            model_name='toptenunlimitsharehold',
            name='hold_num',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='持有无限售条件流通股的数量'),
        ),
        migrations.AlterField(
            model_name='toptenunlimitsharehold',
            name='type_num',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='股份种类数量'),
        ),
    ]
