# Generated by Django 2.0.2 on 2018-05-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0040_auto_20180518_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changinshareholdandremuner',
            name='age',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=22, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='changinshareholdandremuner',
            name='increas_or_decreas_num',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=22, null=True, verbose_name='股份增减变动量'),
        ),
        migrations.AlterField(
            model_name='changinshareholdandremuner',
            name='share_held_num_begin',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=22, null=True, verbose_name='期初持股数'),
        ),
        migrations.AlterField(
            model_name='changinshareholdandremuner',
            name='share_held_num_end',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=22, null=True, verbose_name='期末持股数'),
        ),
        migrations.AlterUniqueTogether(
            name='changinshareholdandremuner',
            unique_together={('stk_cd', 'acc_per', 'name', 'job_titl', 'age', 'name_of_sharehold')},
        ),
    ]
