# Generated by Django 2.0.2 on 2018-04-22 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0040_auto_20180422_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellMajorAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('trade_partner', models.CharField(default='', max_length=150, verbose_name='交易对方')),
                ('asset_sold', models.CharField(default='', max_length=150, verbose_name='被出售资产')),
                ('sale_day', models.CharField(default='', max_length=150, verbose_name='出售日')),
                ('trade_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='交易价格')),
                ('before_net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='本期初起至出售日该资产为上市公司贡献的净利润')),
                ('impact_of_sale', models.CharField(default='', max_length=500, verbose_name='出售对公司的影响')),
                ('proport_net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='资产出售为上市公司贡献的净利润占净利润总额的比例')),
                ('price_principl', models.CharField(default='', max_length=150, verbose_name='资产出售定价原则')),
                ('relat_transa', models.CharField(default='', max_length=150, verbose_name='是否为关联交易')),
                ('connect_relat', models.CharField(default='', max_length=150, verbose_name='与交易对方的关联关系')),
                ('transfer_of_titl', models.CharField(default='', max_length=150, verbose_name='所涉及的资产产权是否已全部过户')),
                ('progress', models.CharField(default='', max_length=500, verbose_name='截至资产负债表日的进展情况')),
                ('debt_transf', models.CharField(default='', max_length=500, verbose_name='所涉及的债权债务是否已全部转移')),
                ('is_on_schedul', models.CharField(default='', max_length=500, verbose_name='是否按计划如期实施')),
                ('date_of_disclosur', models.CharField(default='', max_length=150, verbose_name='披露日期')),
                ('disclosur_index', models.CharField(default='', max_length=150, verbose_name='披露索引')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sellmajorasset',
            unique_together={('stk_cd', 'acc_per', 'trade_partner', 'asset_sold')},
        ),
    ]
