# Generated by Django 2.0.2 on 2018-04-22 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0041_auto_20180422_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellmajorasset',
            name='progress',
        ),
    ]
