# Generated by Django 2.0.2 on 2018-05-20 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0041_auto_20180518_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfReportDownloadRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('disclosure_date', models.CharField(default='', max_length=150, verbose_name='披露日期')),
                ('pdf_url', models.CharField(default='', max_length=300, verbose_name='pdf下载地址')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pdfreportdownloadrecord',
            unique_together={('stk_cd', 'acc_per', 'disclosure_date', 'pdf_url')},
        ),
    ]
