# Generated by Django 2.0.2 on 2018-04-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0042_remove_sellmajorasset_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellmajorasset',
            name='trade_class',
            field=models.CharField(blank=True, choices=[('asset', 'asset'), ('equiti', 'equiti')], max_length=6, verbose_name='资产/股权'),
        ),
        migrations.AlterField(
            model_name='sellmajorasset',
            name='asset_sold',
            field=models.CharField(default='', max_length=150, verbose_name='被出售项目'),
        ),
        migrations.AlterField(
            model_name='sellmajorasset',
            name='before_net_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='本期初起至出售日为上市公司贡献的净利润'),
        ),
        migrations.AlterField(
            model_name='sellmajorasset',
            name='price_principl',
            field=models.CharField(default='', max_length=150, verbose_name='出售定价原则'),
        ),
        migrations.AlterField(
            model_name='sellmajorasset',
            name='proport_net_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='出售为上市公司贡献的净利润占净利润总额的比例'),
        ),
        migrations.AlterField(
            model_name='sellmajorasset',
            name='transfer_of_titl',
            field=models.CharField(default='', max_length=150, verbose_name='是否已全部过户'),
        ),
        migrations.AlterUniqueTogether(
            name='sellmajorasset',
            unique_together={('stk_cd', 'acc_per', 'trade_class', 'trade_partner', 'asset_sold')},
        ),
    ]
