# Generated by Django 2.0.2 on 2018-05-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0042_auto_20180520_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdcompareindex',
            name='market',
            field=models.CharField(default='sz', max_length=2, verbose_name='证券市场'),
        ),
        migrations.AlterUniqueTogether(
            name='pdfreportdownloadrecord',
            unique_together={('stk_cd', 'acc_per')},
        ),
        migrations.AlterUniqueTogether(
            name='stdcompareindex',
            unique_together={('market', 'compare_name')},
        ),
    ]
