# Generated by Django 2.0.2 on 2018-04-22 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0043_auto_20180422_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitAndDisposCom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('name', models.CharField(default='', max_length=150, verbose_name='公司名称')),
                ('acquisit_and_dispos', models.CharField(default='', max_length=150, verbose_name='取得和处置子公司方式')),
                ('impact_on_production', models.CharField(default='', max_length=300, verbose_name='对整体生产经营和业绩的影响')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.CreateModel(
            name='MajorHoldCompani',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('name', models.CharField(default='', max_length=150, verbose_name='公司名称')),
                ('type', models.CharField(default='', max_length=150, verbose_name='公司类型')),
                ('main_bussi', models.CharField(default='', max_length=500, verbose_name='主营业务')),
                ('regist_capit', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='注册资本')),
                ('total_asset', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='总资产')),
                ('net_asset', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='净资产')),
                ('oper_incom', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='营业收入')),
                ('oper_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='营业利润')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='净利润')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='majorholdcompani',
            unique_together={('stk_cd', 'acc_per', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='acquisitanddisposcom',
            unique_together={('stk_cd', 'acc_per', 'name')},
        ),
    ]
