# Generated by Django 2.0.2 on 2018-05-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0043_auto_20180520_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdcompareindex',
            name='fatherno',
            field=models.CharField(default='', max_length=10, verbose_name='父级别编码'),
        ),
        migrations.AlterUniqueTogether(
            name='stdcompareindex',
            unique_together={('market', 'compare_name', 'fatherno')},
        ),
    ]
