# Generated by Django 2.0.2 on 2018-05-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0044_auto_20180520_1838'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workinotherunit',
            unique_together={('stk_cd', 'acc_per', 'name', 'company', 'job_titl')},
        ),
    ]
