# Generated by Django 2.0.2 on 2018-04-24 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0045_busisituatdiscussandanalysi_prospect_future'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountFirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('name', models.CharField(default='', max_length=150, verbose_name='境内会计师事务所名称')),
                ('remuner', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='境内会计师事务所报酬')),
                ('audit_period', models.CharField(default=0, max_length=150, verbose_name='境内会计师事务所审计年限')),
                ('intern_control_name', models.CharField(default='', max_length=150, verbose_name='境内会计师事务所名称')),
                ('intern_control_remuner', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='境内会计师事务所报酬')),
                ('cpa_name', models.CharField(default='', max_length=150, verbose_name='境内注册会计师名称')),
                ('cpa_period', models.CharField(default=0, max_length=150, verbose_name='境内会计师事务所注册会计师审计服务的连续年限')),
                ('oversea_name', models.CharField(default='', max_length=150, verbose_name='境外会计师事务所名称')),
                ('oversea_remuner', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='境外会计师事务所报酬')),
                ('oversea_audit_period', models.CharField(default=0, max_length=150, verbose_name='境外会计师事务所审计年限')),
                ('oversea_cpa_name', models.CharField(default='', max_length=150, verbose_name='境外注册会计师名称')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.CreateModel(
            name='CashDividendPolici',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('number_of_bonu_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='每10股送红股数（股）')),
                ('number_of_dividend', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='每10股派息数(元)（含税）')),
                ('transfer_increas', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='每10股转增数（股）')),
                ('amount_of_cash_divid', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='现金分红的数额（含税）')),
                ('common_sharehold_np', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='分红年度合并报表中归属于上市公司普通股股东的净利润')),
                ('distribut_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='占合并报表中归属于上市公司普通股股东的净利润的比率')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('background', models.TextField(default='', verbose_name='承诺背景')),
                ('type', models.CharField(default='', max_length=150, verbose_name='承诺类型')),
                ('parti', models.CharField(default='', max_length=150, verbose_name='承诺方')),
                ('content', models.TextField(default='', verbose_name='承诺内容')),
                ('time_and_deadline', models.TextField(default='', verbose_name='承诺时间和期限')),
                ('is_there_deadline', models.CharField(default='', max_length=10, verbose_name='是否有履行期限')),
                ('is_strictli_perform', models.CharField(default='', max_length=10, verbose_name='是否严格履行')),
                ('reason_for_incomplet', models.TextField(default='', verbose_name='未能严格履行的原因')),
                ('failur_to_perform', models.TextField(default='', verbose_name='未能及时履行应说明下一步计划')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.CreateModel(
            name='ImportMatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('cash_dividend_polici', models.TextField(default='', verbose_name='现金分红政策')),
                ('distribute_plan', models.TextField(default='', verbose_name='分配方案')),
                ('commit', models.TextField(default='', verbose_name='承诺事项')),
                ('profit_predict', models.TextField(default='', verbose_name='盈利预测')),
                ('account_firm', models.TextField(default='', verbose_name='聘任、解聘会计师事务所情况')),
                ('relat_transact_desc', models.TextField(default='', verbose_name='关联交易情况')),
                ('big_sale_return_rt', models.TextField(default='', verbose_name='关联交易中大额销货退回的详细情况')),
                ('perf_agre_rt', models.TextField(default='', verbose_name='关联股权收购交易中的业绩约定实现情况')),
                ('other_major_issu', models.TextField(default='', verbose_name='其他重大事项的说明')),
                ('social_respons_work', models.TextField(default='', verbose_name='社会责任工作情况')),
                ('outsid_of_key_emitt', models.TextField(default='', verbose_name='重点排污单位之外的公司')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.CreateModel(
            name='ProfitPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('asset_or_project_nam', models.CharField(default='', max_length=300, verbose_name='盈利预测资产或项目名称')),
                ('start_time', models.CharField(default='', max_length=100, verbose_name='预测起始时间')),
                ('end_time', models.CharField(default='', max_length=100, verbose_name='预测终止时间')),
                ('forecast_perform', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='当期预测业绩')),
                ('actual_result', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='当期实际业绩')),
                ('unpredict_reason', models.TextField(default='', verbose_name='未达预测的原因')),
                ('origin_disclosur_date', models.CharField(default='', max_length=100, verbose_name='原预测披露的日期')),
                ('origin_disclosur_index', models.CharField(default='', max_length=100, verbose_name='原预测披露的索引')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.CreateModel(
            name='RelatTransact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('dealer', models.CharField(default='', max_length=150, verbose_name='关联交易方')),
                ('relationship', models.CharField(default='', max_length=150, verbose_name='关联关系')),
                ('transact_type', models.CharField(default='', max_length=150, verbose_name='关联交易类型')),
                ('transact_content', models.CharField(default='', max_length=150, verbose_name='关联交易内容')),
                ('price_principl', models.CharField(default='', max_length=150, verbose_name='关联交易定价原则')),
                ('trade_price', models.CharField(default='', max_length=150, verbose_name='关联交易价格')),
                ('transact_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='关联交易金额')),
                ('proport_of_similar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='占同类交易金额的比例')),
                ('approv_transact_amou', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='获批的交易额度')),
                ('exceed_approv_amou', models.CharField(default='', max_length=10, verbose_name='是否超过获批额度 ')),
                ('bill_method', models.CharField(default='', max_length=150, verbose_name='关联交易结算方式')),
                ('market_price', models.CharField(default='', max_length=150, verbose_name='市场价格')),
                ('price_diff_reason', models.CharField(default='', max_length=300, verbose_name='交易价格与市场参考价格差异较大的原因')),
                ('stk_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='relattransact',
            unique_together={('stk_cd', 'acc_per', 'dealer', 'transact_type', 'transact_content')},
        ),
        migrations.AlterUniqueTogether(
            name='profitpredict',
            unique_together={('stk_cd', 'acc_per', 'asset_or_project_nam')},
        ),
        migrations.AlterUniqueTogether(
            name='importmatter',
            unique_together={('stk_cd', 'acc_per')},
        ),
        migrations.AlterUniqueTogether(
            name='commit',
            unique_together={('stk_cd', 'acc_per', 'background', 'type', 'parti', 'content')},
        ),
        migrations.AlterUniqueTogether(
            name='cashdividendpolici',
            unique_together={('stk_cd', 'acc_per')},
        ),
        migrations.AlterUniqueTogether(
            name='accountfirm',
            unique_together={('stk_cd', 'acc_per')},
        ),
    ]
