# Generated by Django 2.0.2 on 2018-05-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0045_auto_20180521_1543'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='changinshareholdandremuner',
            unique_together={('stk_cd', 'acc_per', 'name', 'job_titl', 'age', 'name_of_sharehold', 'job_titl_in_sharehold_com')},
        ),
    ]
