# Generated by Django 2.0.2 on 2018-04-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0046_auto_20180424_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdividendpolici',
            name='distribut_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='可分配利润'),
        ),
        migrations.AddField(
            model_name='cashdividendpolici',
            name='prop_of_distribut_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='可分配利润'),
        ),
        migrations.AddField(
            model_name='commit',
            name='deadline',
            field=models.CharField(default='', max_length=150, verbose_name='承诺期限'),
        ),
        migrations.AddField(
            model_name='commit',
            name='perform',
            field=models.TextField(default='', verbose_name='履行情况'),
        ),
        migrations.AddField(
            model_name='commit',
            name='time',
            field=models.CharField(default='', max_length=150, verbose_name='承诺时间'),
        ),
        migrations.AddField(
            model_name='importmatter',
            name='posit_profit_no_divi',
            field=models.TextField(default='', verbose_name='报告期内盈利且母公司可供普通股股东分配利润为正但未提出普通股现金红利分配预案的原因'),
        ),
        migrations.AlterField(
            model_name='accountfirm',
            name='intern_control_remuner',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='境内会计师事务所报酬'),
        ),
        migrations.AlterField(
            model_name='accountfirm',
            name='oversea_remuner',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='境外会计师事务所报酬'),
        ),
        migrations.AlterField(
            model_name='accountfirm',
            name='remuner',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='境内会计师事务所报酬'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='parti',
            field=models.CharField(default='', max_length=500, verbose_name='承诺方'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='time_and_deadline',
            field=models.CharField(default='', max_length=150, verbose_name='承诺时间和期限'),
        ),
        migrations.AlterField(
            model_name='profitpredict',
            name='actual_result',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='当期实际业绩'),
        ),
        migrations.AlterField(
            model_name='profitpredict',
            name='forecast_perform',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='当期预测业绩'),
        ),
        migrations.AlterField(
            model_name='relattransact',
            name='approv_transact_amou',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='获批的交易额度'),
        ),
        migrations.AlterField(
            model_name='relattransact',
            name='proport_of_similar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='占同类交易金额的比例'),
        ),
        migrations.AlterField(
            model_name='relattransact',
            name='transact_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='关联交易金额'),
        ),
    ]
