# Generated by Django 2.0.2 on 2018-05-21 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0046_auto_20180521_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkInSharehold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_per', models.DateField(verbose_name='会计期间')),
                ('name_of_sharehold', models.CharField(default='', max_length=150, verbose_name='股东单位名称')),
                ('job_titl_in_sharehold_com', models.CharField(default='', max_length=150, verbose_name='在股东单位担任的职务')),
                ('start_date_in_sharehold_com', models.CharField(default='', max_length=150, verbose_name='在股东单位任期起始日期')),
                ('end_date_in_sharehold_com', models.CharField(default='', max_length=150, verbose_name='在股东单位任期终止日期')),
                ('job_titl_chang_reason', models.TextField(default='', verbose_name='任职变动原因')),
            ],
        ),
        # migrations.RemoveField(
        #     model_name='changinshareholdandremuner',
        #     name='end_date_in_sharehold_com',
        # ),
        # migrations.RemoveField(
        #     model_name='changinshareholdandremuner',
        #     name='job_titl_chang_reason',
        # ),
        # migrations.RemoveField(
        #     model_name='changinshareholdandremuner',
        #     name='job_titl_in_sharehold_com',
        # ),
        # migrations.RemoveField(
        #     model_name='changinshareholdandremuner',
        #     name='name_of_sharehold',
        # ),
        # migrations.RemoveField(
        #     model_name='changinshareholdandremuner',
        #     name='start_date_in_sharehold_com',
        # ),
        migrations.AlterUniqueTogether(
            name='changinshareholdandremuner',
            unique_together={('stk_cd', 'acc_per', 'name', 'job_titl', 'age')},
        ),
        migrations.AddField(
            model_name='workinsharehold',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.ChangInShareholdAndRemuner'),
        ),
        migrations.AddField(
            model_name='workinsharehold',
            name='stk_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyList', verbose_name='股票代码'),
        ),
        migrations.AlterUniqueTogether(
            name='workinsharehold',
            unique_together={('stk_cd', 'acc_per', 'name', 'name_of_sharehold', 'job_titl_in_sharehold_com')},
        ),
    ]
