# Generated by Django 2.0.2 on 2018-05-23 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0049_auto_20180523_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text2Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=150, verbose_name='原始字段文本')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.FieldDesc', verbose_name='标准字段')),
                ('indexno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.StdContentIndex', verbose_name='标准索引')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.TableDesc', verbose_name='表名')),
            ],
        ),
        migrations.RenameField(
            model_name='comprehensnote',
            old_name='capit_reserv',
            new_name='cptl_rsrv',
        ),
        migrations.AlterField(
            model_name='accountfirm',
            name='intern_control_name',
            field=models.CharField(default='', max_length=150, verbose_name='内部控制审计会计师事务所'),
        ),
        migrations.AlterField(
            model_name='accountfirm',
            name='intern_control_remuner',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='内部控制审计会计师事务所报酬'),
        ),
        migrations.AlterUniqueTogether(
            name='text2field',
            unique_together={('indexno', 'table', 'text')},
        ),
    ]
