# Generated by Django 2.0.2 on 2018-05-24 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0051_auto_20180523_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='longtermequitiinvest',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='overduinterest',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='returnbaddebtpreparlist',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='significreceiv',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='top5receiv',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='writeoffreceiv',
            old_name='name',
            new_name='company_name',
        ),
        migrations.AlterField(
            model_name='ageanalysi',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='commonbalancimpairnet',
            name='balanc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='账面余额'),
        ),
        migrations.AlterField(
            model_name='fixassetstatu',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.FixAndIntangAssetType', verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='parentcompaniandactualcontrol',
            name='instruct',
            field=models.TextField(default='', verbose_name='详细说明'),
        ),
        migrations.AlterField(
            model_name='reportdivisfinanciinform',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyName', verbose_name='报告分部'),
        ),
        migrations.AlterField(
            model_name='transactimpactinchangeshareofsubsidiari',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.CompanyName', verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='unfinishproperti',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='项目名称'),
        ),
        migrations.AlterUniqueTogether(
            name='longtermequitiinvest',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'company_name')},
        ),
        migrations.AlterUniqueTogether(
            name='overduinterest',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'company_name')},
        ),
        migrations.AlterUniqueTogether(
            name='returnbaddebtpreparlist',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'before_end', 'subject', 'company_name')},
        ),
        migrations.AlterUniqueTogether(
            name='significreceiv',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'before_end', 'subject', 'company_name')},
        ),
        migrations.AlterUniqueTogether(
            name='top5receiv',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'before_end', 'subject', 'company_name')},
        ),
        migrations.AlterUniqueTogether(
            name='writeoffreceiv',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'before_end', 'subject', 'company_name')},
        ),
    ]
