# Generated by Django 2.0.2 on 2018-05-24 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0052_auto_20180524_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixasset',
            old_name='asset_type',
            new_name='asset_categori',
        ),
        migrations.AlterUniqueTogether(
            name='fixasset',
            unique_together={('stk_cd', 'acc_per', 'typ_rep', 'asset_categori', 'valu_categori', 'item', 'increas_cut_back_type', 'amount_type')},
        ),
    ]
