# Generated by Django 2.0.2 on 2018-05-24 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0053_auto_20180524_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changinordinarishare',
            old_name='project',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='changinordinarishare',
            unique_together={('stk_cd', 'acc_per', 'name')},
        ),
    ]
