# Generated by Django 2.0.2 on 2018-05-24 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0054_auto_20180524_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerboseName2Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose', models.CharField(default='', max_length=200, unique=True, verbose_name='verbose_name')),
                ('field', models.CharField(default='', max_length=200, verbose_name='field_name')),
            ],
        ),
        migrations.AlterField(
            model_name='companibasicsituat',
            name='signific_amount_judgement',
            field=models.TextField(default='', verbose_name='单项金额重大的判断依据或金额标准'),
        ),
        migrations.AlterField(
            model_name='companibasicsituat',
            name='signific_amount_withdraw',
            field=models.TextField(default='', verbose_name='单项金额重大并单项计提坏账准备的计提方法'),
        ),
        migrations.AlterField(
            model_name='text2field',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.VerboseName2Field', verbose_name='标准字段'),
        ),
    ]
