# Generated by Django 2.0.2 on 2018-05-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0055_auto_20180524_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddesc',
            name='choices',
            field=models.TextField(blank=True, default='', verbose_name='选项'),
        ),
        migrations.AddField(
            model_name='fielddesc',
            name='foreignkey',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='外键'),
        ),
        migrations.AddField(
            model_name='fielddesc',
            name='is_unique',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='是否唯一'),
        ),
        migrations.AddField(
            model_name='tabledesc',
            name='unique_together',
            field=models.CharField(default='', max_length=300, verbose_name='联合唯一'),
        ),
    ]
