# Generated by Django 2.0.2 on 2018-05-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0056_auto_20180524_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn_name', models.CharField(default='', max_length=150, unique=True, verbose_name='中文名称')),
                ('en_name', models.CharField(default='', max_length=300, unique=True, verbose_name='英文名称')),
                ('en_ab_name', models.CharField(default='', max_length=150, unique=True, verbose_name='英文缩写')),
                ('level', models.CharField(default='', max_length=10, verbose_name='科目层次')),
                ('fatherno', models.CharField(default='', max_length=10, verbose_name='父级编码')),
                ('selfrno', models.CharField(default='', max_length=10, verbose_name='自身编码')),
                ('no', models.CharField(default='', max_length=10, verbose_name='索引完整编号')),
                ('desc', models.TextField(default='', verbose_name='描述')),
            ],
        ),
    ]
