# Generated by Django 2.0.2 on 2018-05-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0057_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='selfrno',
            new_name='selfno',
        ),
    ]
