# Generated by Django 2.0.2 on 2018-05-25 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0059_auto_20180524_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreigncurrencitem',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.Subject', verbose_name='科目名称'),
        ),
    ]
