# Generated by Django 2.0.2 on 2018-05-27 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0060_auto_20180525_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.TextField(default='', verbose_name='列字段')),
                ('indexes', models.TextField(default='', verbose_name='行字段')),
                ('indexno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.StdContentIndex', verbose_name='标准索引')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tableattr',
            unique_together={('indexno', 'columns', 'indexes')},
        ),
    ]
