# Generated by Django 2.0.2 on 2018-05-28 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0061_auto_20180527_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indexno2Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(default='', max_length=150, verbose_name='表名')),
                ('indexno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.StdContentIndex', verbose_name='标准索引')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.TableDesc', verbose_name='表名')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='indexno2table',
            unique_together={('indexno', 'table')},
        ),
    ]
