# Generated by Django 2.0.2 on 2018-05-28 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data_extract', '0062_auto_20180528_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handleclass2Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(default='', max_length=150, verbose_name='表名')),
                ('handleclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.IndexHandleMethod', verbose_name='类处理名称')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.TableDesc', verbose_name='表')),
            ],
        ),
        migrations.AlterField(
            model_name='indexno2table',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data_extract.TableDesc', verbose_name='表'),
        ),
        migrations.AlterUniqueTogether(
            name='handleclass2table',
            unique_together={('handleclass', 'table')},
        ),
    ]
